### ISSUE TITLE
Choose a more specific name than "signing-spec"

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/signing-spec#16]
"signing-spec" is a generic working title for this repo/project/specification. It should be replaced by something more specific.

Side-goal courtesy of @MarkLodato: Ideally the new name is easy to search for.

See [#1 - What is secure-systems-lab/signing-spec?](https://github.com/secure-systems-lab/signing-spec/issues/1) for context.

**Comment by adityasaky** [comment]
It's probably past time to kickstart this. Does anyone have any thoughts on what we can name this spec? Any initial leads we could iterate over?

**Comment by TomHennen** [comment]
Some random thoughts: 

JSON Artifact Envelope - JAE - Not great because it's not actually an envelope for artifacts.
involucrum - Latin for envelope.  Using Latin to play off of in-toto. Probably pretty awkward to say.
JSON Signed Envelope - JSE
in-toto Attestation Envelope - IAE (maybe we don't want to reference in-toto?)

**Comment by MarkLodato** [comment]
More ideas:
- ["envelope"](https://www.indifferentlanguages.com/words/envelope) or ["signature"](https://www.indifferentlanguages.com/words/signature) in another language.
- "Foolproof Signed Envelope"
- "Dead Simple Signed Envelope", pronounced "dissy"

**Comment by adityasaky** [comment]
I like Dead Simple Signed Envelope! I was considering options along the lines of "Lightweight", but I think this may be crisper.

**Comment by MarkLodato** [comment]
Another option that is more descriptive:
- "Signed Type-Identified Message" (STIM)
- "Signed Message with Authenticated Type" (SMAT)
- or similar

If we think about the advantages of this spec over others, the main thing is that it authenticates the type in addition to the message. The only other spec that provides that is JWS (via `typ`), but that spec is super complicated and error-prone.

**Comment by TomHennen** [comment]
Type Authenticated Cryptographic Object - TACO

🌮

**Comment by MarkLodato** [comment]
Oh man, I love it! Too bad the name is overly broad!

**Comment by MarkLodato** [comment]
tamale: Type And Message Authenticated in a Lightweight Envelope

**Comment by trishankatdatadog** [comment]
I vote DSSE

**Comment by MarkLodato** [comment]
I have a slight preference for tamale but am fine with DSSE.

Any more votes?

I suggest that we go with DSSE unless we hear any dissenting opinions within the next few days.

**Comment by TomHennen** [comment]
I'm fine with either.

**Comment by adityasaky** [comment]
I'm fine with either as well.
