### ISSUE TITLE
Create a reference implementation and test vectors

### ISSUE THREAD

**Issue by MarkLodato** [secure-systems-lab/signing-spec#28]

**Comment by adityasaky** [comment]
As @dlorenc pointed out on #21, https://github.com/in-toto/in-toto-golang/tree/master/pkg/ssl adds support for this spec in in-toto-golang. Do we want to discuss using it as a standalone reference implementation and build on top of it?

**Comment by MarkLodato** [comment]
We already have a Python implementation. I suggest that that is good enough. Any objections?

**Comment by TomHennen** [comment]
OH, do we, where can we find it?  Is it in here?
https://github.com/in-toto/in-toto/tree/develop/in_toto

**Comment by adityasaky** [comment]
https://github.com/secure-systems-lab/signing-spec/tree/master/implementation
