### ISSUE TITLE
Clarify encoding of payload type in PAE

### ISSUE THREAD

**Issue by MarkLodato** [secure-systems-lab/signing-spec#3]
The spec does not define how to encode the PAE string values, particularly the payload type. Currently it says:

```json
{
  "payload": "<Base64(SERIALIZED_BODY)>",
  "payloadType": "<PAYLOAD_TYPE>",
  "signatures": [{
    …,
    "sig": "<Base64(Sign(PAE([PAYLOAD_TYPE, SERIALIZED_BODY])))>"
  }, …]
}
```

```
PAE([type, body]) := le64(2) || le64(len(type)) || type || le64(len(body)) || body
```

The problem is that `PAYLOAD_TYPE` is a unicode string, whereas the `type` parameter of PAE needs to be a byte sequence. The doc should specify that UTF-8 encoding is required. (It can be something else, but UTF-8 is unambiguous an simple, so I suggest that.)

While we're at it, we should clarify that `SERIALIZED_BODY` is a byte sequence, thus unambiguous.

Perhaps the best solution is to first define these variables and their types.

I'll send a pull request to address.

**Comment by trishankatdatadog** [comment]
Great clarification, thanks! I think we should also have small, working Python pseudocode to make sure we don't miss anything.
