### ISSUE TITLE
Backwards compatible `payloadType` should be an exact match

### ISSUE THREAD

**Issue by MarkLodato** [secure-systems-lab/signing-spec#5]
With 2c38369, the backward compatible `payloadType` was changed to a suffix match. This has two disadvantages over an exact match:

* It provides a false sense of security since the prefix is unauthenticated. An attacker could change a legitimate signature's `payloadType` from `foo/backwards-compatible-json` to `bar/backwards-compatible-json` without invalidating the signature. If the consumer relies on `payloadType`, this could be a security vulnerability. Using an exact match avoids this.
* (minor) It is ever-so-slightly harder to describe and implement.

I recommend making it a fixed string.

By the way, the reason I originally wrote it as a non-URI string was so that URI always meant PAE and all magic values were non-URIs. I don't have a problem with having a magic URI, but just FYI in case you want to switch back to the original value. (I don't feel strongly.)

**Comment by trishankatdatadog** [comment]
Agree with the exact match of payloadType.

I think it's helpful to make it a URI so that curious readers can look up more information about custom payload types, if interested. Optionality without breaking security (so long as machine clients don't open or parse these URLs automatically for whatever reason).

**Comment by MarkLodato** [comment]
Then again, this is specifically about in-toto and TUF backwards compatibility, so I suppose that URI actually does make sense. :)
